sudo: required #need super user rights
language: generic 


services: 
  - docker

before_install: 
  - docker build -t biohazard/docker-react -f DockerFile.dev .

script:
  - docker run -e CI=true biohazard/docker-react npm run test