sudo: required #need super user rights
language: generic 


services: 
  - docker

before_install: 
  - docker build -t biohazard/docker-react -f DockerFile.dev .

script:
  - docker run -e CI=true biohazard/docker-react npm run test

deploy:
    provider: elasticbeanstalk # pre configured by tavi
    region: "ap-northeast-1"
    app: "docker-react"
    env: "Dockerreact-env"
    bucket_name: "elasticbeanstalk-ap-northeast-1-088634564569"
    bucket_path: "docker-react"
    on:
      branch: master

    access_key_id: $AWS_ACCESS_KEY
    secret_acess_key: "$AWS_SECRET_KEY"